### ISSUE TITLE
Can't get the preview thumbnails to work (Docker)

### ISSUE THREAD

**Issue by 29axe** [danrahn/MarkerEditorForPlex#34]
**Describe the bug**
I don't have thumbnails, even with all options enabled.
I tried pressing keyboard keys 't' and 'enter' but nothing. Also the "thumbnails" icon is not appearing in the 'options' of the edition row, only "chapters" but greyed out.

I tried without ffmpeg first, then added ffmpeg to the docker image.
I tried latest and beta image tags.
My library is in a different dir than Plex (/share/Plex) on the same server. I tried adding a volume to my Plex library using the same path so that marker editor can follow paths to files from plex db.
I tried overriding the PlexData path in server settings with the path to my library (added in volume) but it is replaced with /PlexDataDirectory after clicking save.
I tried path mappings in server settings with no luck.

Any help appreciated.

**To Reproduce**
1. Go to episode
2. Click on 'add thumbnail' or 'edit'
4. Press any shortcuts or wait for thumnails to auto load but nothing appears

**Expected behavior**
Get thumbnails to work

**Screenshots**

![Image](https://github.com/user-attachments/assets/cb4ed87c-d8a7-4351-b9dd-96861c541255)

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Opera, Firefox
 - Version latest and beta

**Comment by danrahn** [comment]
Unfortunately I'm very unfamiliar with Docker, so might not be that helpful as far as troubleshooting goes. The fact that there isn't a thumbnail icon though indicates that it wasn't able to find ffmpeg, and it wasn't able to find/read your data path.

> I tried overriding the PlexData path in server settings with the path to my library (added in volume) but it is replaced with /PlexDataDirectory after clicking save.

That's a bug that I should fix, as the data path/database fields fields shouldn't be editable when running in a Docker container. Due to my unfamiliarity with Docker, it's designed so that you _must_ mount your [data directory](https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/) to `/PlexDataDirectory` outside of this application (e/g/ `-v /path/to/PlexMediaServer:/PlexDataDirectory`).

**Comment by Sproglet** [comment]
Try this run command. I used it before I created my own Docker image:

```
docker run -p 3232:3232 \
           -v /opt/plex-marker-editor/config:/Data \
           -v path_to_plex/Library/Application\ Support/Plex\ Media\ Server:/PlexDataDirectory \
           -d \
           --name intro-editor-for-plex \
           -v /media:/media:ro \
           -it danrahn/intro-editor-for-plex:latest bash -c "apt update && apt install -y ffmpeg && node app.js"
```
_Note both sides of the media mount should be the same so the media can be seen by the app_
_If you have movies and TV in different root folders add them all like the media one in this example_

**Comment by D3r3k23** [comment]
I think that to use ffmpeg in Docker you need to install it in the Dockerfile like @Sproglet has in his fork.

**Comment by 29axe** [comment]
Sorry I forgot to give a feedback on this one.
I managed to make it work at that time, by using a custom docker image based on @danrahn's image.

```Dockerfile
FROM danrahn/intro-editor-for-plex:beta

RUN apt-get update && apt-get install -y ffmpeg
``` 

And my docker-compose.yaml:

```yml
services:
  plex-marker-editor:
    # image: danrahn/intro-editor-for-plex:ffmpeg
    build:
      context: .
    ports:
      - "3232:3232"
    volumes:
      - config:/Data  # path to config of plex-marker-editor (here, config is in current dir)
      - /share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Library/Plex Media Server:/PlexDataDirectory  # path to the database of plex media server (here, for Plex app installed on a QNAP NAS)
      - /<path-to-plex>/Plex:/share/Plex  # path to plex media libraries (videos)
    tty: true
```

**Comment by D3r3k23** [comment]
Thanks for sharing that. Although it's not ideal for my setup on Unraid. Should this just be added to the Dockerfile for the base image?
`RUN apt-get update && apt-get install -y ffmpeg`

**Comment by 29axe** [comment]
I don't know how you manage your containers on your NAS but here are the steps needed to build the image with ffmpeg:

You just need to create a file named `Dockerfile` wherever you want and paste this inside:
```Dockerfile
FROM danrahn/intro-editor-for-plex:beta

RUN apt-get update && apt-get install -y ffmpeg
```
_You can base your image on `:latest` or `:beta`._
Then you build your image using `docker build . -t  danrahn/intro-editor-for-plex:ffmpeg`, in the directory where you placed your Dockerfile.
After that you can use your image `danrahn/intro-editor-for-plex:ffmpeg` for deployment:

```sh
docker run -p 3233:3232 \
           -v /path/to/config:/Data \
           -v /path/to/PlexData:/PlexDataDirectory \
           -it danrahn/intro-editor-for-plex:ffmpeg
```

Or you can use this image I just pushed instead: `29axe/intro-editor-for-plex:ffmpeg`

**Comment by collumbrian** [comment]
Hmm, i did what 29axe suggested but still no thumbnail loads. 

<img width="439" height="449" alt="Image" src="https://github.com/user-attachments/assets/49543ff8-a853-42d3-850d-aae72b3795ca" />

I tried his conatiner and also when back to danrahn's latest and modified my compose file to install ffmpeg first:
```
    # Install ffmpeg before running app.js (normal command)
    command: bash -c "apt update && apt install -y ffmpeg && node app.js"
```

So ffmpeg is installed now, but it's still not loading any thumbnails. I'm assuming they are just supposed to pop up when you go to view markers or edit them right? I don't get empty boxes or anything there.

Regardless, awesome tool. Plex was screwing up detection on 3 seasons of a show and it was driving me nuts that it kept skipping random parts of the episode so this let me correct those.
